// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/grok": {
            "get": {
                "description": "Create, read, update, and delete Grok patterns for log parsing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grok"
                ],
                "summary": "Manage Grok patterns",
                "parameters": [
                    {
                        "description": "Grok pattern definition",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.GrokPatternRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response with patterns",
                        "schema": {
                            "$ref": "#/definitions/types.GrokPatternResponse"
                        }
                    },
                    "201": {
                        "description": "Pattern created successfully",
                        "schema": {
                            "$ref": "#/definitions/types.GrokPatternResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or missing required fields",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pattern not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create, read, update, and delete Grok patterns for log parsing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grok"
                ],
                "summary": "Manage Grok patterns",
                "parameters": [
                    {
                        "description": "Grok pattern definition",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.GrokPatternRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response with patterns",
                        "schema": {
                            "$ref": "#/definitions/types.GrokPatternResponse"
                        }
                    },
                    "201": {
                        "description": "Pattern created successfully",
                        "schema": {
                            "$ref": "#/definitions/types.GrokPatternResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or missing required fields",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pattern not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Create, read, update, and delete Grok patterns for log parsing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grok"
                ],
                "summary": "Manage Grok patterns",
                "parameters": [
                    {
                        "description": "Grok pattern definition",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.GrokPatternRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response with patterns",
                        "schema": {
                            "$ref": "#/definitions/types.GrokPatternResponse"
                        }
                    },
                    "201": {
                        "description": "Pattern created successfully",
                        "schema": {
                            "$ref": "#/definitions/types.GrokPatternResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or missing required fields",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pattern not found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Retrieve detailed information about the system, storage, and application",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get system and storage information",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Force a cache refresh if set to true",
                        "name": "refresh",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SystemInfoResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ingest/end": {
            "post": {
                "description": "End the specified log ingest session and cleanup its resources",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "End log ingest session",
                "parameters": [
                    {
                        "description": "Session end request with session_id",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.IngestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.IngestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ingest/file": {
            "post": {
                "description": "Start ingesting a log file the server can access (absolute path; gzip and zstd are detected by magic bytes) into an existing ingest session, optionally with its rotated siblings. Accepted immediately (202); the read runs in the background. Poll GET /ingest/jobs or listen for \"ingest_progress\" on GET /live/events for progress and the final state. Call POST /ingest/end only after the job reaches a terminal state (done|cancelled|error) -- ending the session while the job is still running fails its next batch with an invalid-session error.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Ingest a file by path",
                "parameters": [
                    {
                        "description": "Session and absolute path",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.IngestFileRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/types.IngestFileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ingest/jobs": {
            "get": {
                "description": "List every path-based ingest job started this server run (running or finished), for a UI reconnecting to a job it lost SSE contact with.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "List path-ingest jobs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.IngestJobsListResponse"
                        }
                    }
                }
            }
        },
        "/ingest/jobs/{id}": {
            "delete": {
                "description": "Cancel a running path-based ingest job. A no-op (200, the job's own terminal state) if it already finished.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Cancel a path-ingest job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.IngestJobActionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ingest/logs": {
            "post": {
                "description": "Ingest log data using existing Grok patterns and store them into the index",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Ingest log data",
                "parameters": [
                    {
                        "description": "Log ingest request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.IngestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.IngestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ingest/start": {
            "post": {
                "description": "Start a new log ingest session with specific options and returns a session ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Start log ingest session",
                "parameters": [
                    {
                        "description": "Log ingest session start request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.IngestSessionOptions"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.IngestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logs": {
            "get": {
                "description": "Retrieve all stored logs with pagination, sorting, time distribution support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Read all logs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of logs to return (default: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of logs to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to sort by (default: timestamp)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc or desc, default: desc)",
                        "name": "sort_order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date for log retrieval (RFC3339 format)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date for log retrieval (RFC3339 format)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional search query to filter logs",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional comma-separated source filter",
                        "name": "_src",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional comma-separated fields to return",
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include chart distribution metadata (default: true)",
                        "name": "include_distribution",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include a field/value facet summary of the window (default: false; bounded scan of the newest rows, see facets.computed_over/sampled)",
                        "name": "include_facets",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Logs with pagination, sorting, and time distribution metadata",
                        "schema": {
                            "$ref": "#/definitions/types.LogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request due to invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete all stored logs from the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Clear all logs",
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logs/delete": {
            "post": {
                "description": "Delete specific logs from the system identified by their document IDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Delete logs by IDs",
                "parameters": [
                    {
                        "description": "IDs of logs to delete",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DeleteLogsByIdsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message with deletion statistics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request due to invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/parse": {
            "post": {
                "description": "Parse logs using existing or temporary Grok patterns without storing them into the database.\nIf no grok_pattern is provided, this endpoint will suggest the best matching patterns for the logs.\nWhen a grok_pattern is provided, it will parse the logs using that pattern.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parsing"
                ],
                "summary": "Parse logs or suggest patterns",
                "parameters": [
                    {
                        "description": "Log parsing request with optional grok_pattern and custom_patterns",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ParseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Autosuggest results when no pattern provided",
                        "schema": {
                            "$ref": "#/definitions/types.SuggestResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or pattern",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/parse/preview-file": {
            "post": {
                "description": "Read the first few lines of a file the server can access (absolute path; gzip and zstd detected by magic bytes), without creating an ingest session. Used by the native-drop wizard flow, which only ever has a path, not a browser File to read.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Preview a file by path",
                "parameters": [
                    {
                        "description": "Absolute path and optional line count",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.PreviewFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.PreviewFileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Check if the API is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Ping the API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.PingResponse"
                        }
                    }
                }
            }
        },
        "/sources": {
            "get": {
                "description": "Every source in the catalog (\u003cstorage\u003e/sources.json): origin, pattern, rows, bytes, timestamp span, the day-indices holding it, and its import history. Maintained on the ingest write path; see POST /sources/rebuild to reconcile with the indices.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "List sources",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SourcesResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sources/rebuild": {
            "post": {
                "description": "Recomputes rows, days and timestamp bounds for every source from the day-indices (one size-0 facet per day on current indices; a stored-field read on indices created before v1.8's keyword _src mapping). Origin, pattern and import history are kept; sources with no rows left are dropped. Idempotent.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Rebuild the sources catalog from the indices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SourcesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sources/{name}": {
            "get": {
                "description": "One catalog entry by source name (the stored _src value).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Get one source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SourceEntry"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/timestamp/preview": {
            "post": {
                "description": "Re-renders the timestamp inference and preview rows for\na sample of log lines using the supplied Resolution.\nUsed by the import wizard's timestamp panel to show a\nlive preview as the user changes knobs (anchor, year\nstrategy, timezone, force mode, rollover) without\nre-running the full /parse path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parsing"
                ],
                "summary": "Preview timestamp resolution",
                "parameters": [
                    {
                        "description": "Timestamp preview request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.TimestampPreviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TimestampPreviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspaces"
                ],
                "summary": "List saved investigation workspaces",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.WorkspaceListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspaces"
                ],
                "summary": "Create a saved investigation workspace",
                "parameters": [
                    {
                        "description": "Workspace",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Workspace"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.WorkspaceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspaces"
                ],
                "summary": "Get a saved investigation workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.WorkspaceResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspaces"
                ],
                "summary": "Update a saved investigation workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Workspace",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Workspace"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.WorkspaceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "workspaces"
                ],
                "summary": "Delete a saved investigation workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/{id}/duplicate": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspaces"
                ],
                "summary": "Duplicate a saved investigation workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.WorkspaceResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.DeleteLogsByIdsRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.PingResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.TimestampPreviewRequest": {
            "type": "object",
            "properties": {
                "custom_patterns": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "grok_pattern": {
                    "type": "string"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resolution": {
                    "$ref": "#/definitions/timeresolve.Resolution"
                },
                "source_mtime": {
                    "type": "string"
                }
            }
        },
        "handlers.TimestampPreviewResponse": {
            "type": "object",
            "properties": {
                "inference": {
                    "$ref": "#/definitions/timeresolve.Inference"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "timeresolve.Anchor": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "timeresolve.FieldCandidate": {
            "type": "object",
            "properties": {
                "format": {
                    "description": "detected format hint (auto / unix_seconds / Go layout)",
                    "type": "string"
                },
                "name": {
                    "description": "capture name",
                    "type": "string"
                },
                "parsed": {
                    "description": "RFC3339 result when Parses",
                    "type": "string"
                },
                "parses": {
                    "description": "could be parsed as a timestamp",
                    "type": "boolean"
                },
                "sample": {
                    "description": "first observed value",
                    "type": "string"
                },
                "score": {
                    "description": "ranking used for auto-pick (higher = better)",
                    "type": "integer"
                }
            }
        },
        "timeresolve.Inference": {
            "type": "object",
            "properties": {
                "field_candidates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeresolve.FieldCandidate"
                    }
                },
                "layout": {
                    "$ref": "#/definitions/timeresolve.Layout"
                },
                "preview": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/timeresolve.PreviewRow"
                    }
                },
                "resolution": {
                    "$ref": "#/definitions/timeresolve.Resolution"
                },
                "status": {
                    "type": "string"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "timeresolve.Layout": {
            "type": "object",
            "properties": {
                "components_present": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "has_timestamp_field": {
                    "type": "boolean"
                },
                "inferred_format_label": {
                    "type": "string"
                },
                "year_width": {
                    "description": "0=year-less, 2, or 4",
                    "type": "integer"
                }
            }
        },
        "timeresolve.PreviewRow": {
            "type": "object",
            "properties": {
                "captured": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "confidence": {
                    "type": "string"
                },
                "raw": {
                    "type": "string"
                },
                "resolved": {
                    "type": "string"
                }
            }
        },
        "timeresolve.Resolution": {
            "type": "object",
            "properties": {
                "anchor": {
                    "$ref": "#/definitions/timeresolve.Anchor"
                },
                "force_mode": {
                    "type": "string"
                },
                "forced_day": {
                    "type": "integer"
                },
                "forced_month": {
                    "type": "integer"
                },
                "forced_year": {
                    "type": "integer"
                },
                "rollover": {
                    "type": "boolean"
                },
                "source_field": {
                    "description": "SourceField names a non-canonical capture to use as the line's\ntimestamp string. When set, the resolver reads fields[SourceField]\ninstead of probing the canonical names (timestamp/date/time/...).\nEmpty means \"use canonical scan\" (the legacy default).",
                    "type": "string"
                },
                "source_format": {
                    "description": "SourceFormat hints how to parse SourceField's value. Empty means\nauto-detect via dateparse + unix-epoch length heuristics. Special\nvalues: \"unix_seconds\" / \"unix_millis\" / \"unix_nanos\". Anything\nelse is treated as a Go time layout (e.g. \"2006-01-02-15.04.05.000000\"\nfor the BGL supercomputer format).",
                    "type": "string"
                },
                "timezone": {
                    "$ref": "#/definitions/timeresolve.TimezoneCfg"
                },
                "year_strategy": {
                    "type": "string"
                }
            }
        },
        "timeresolve.TimezoneCfg": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "value": {
                    "description": "IANA zone name when Kind=forced",
                    "type": "string"
                }
            }
        },
        "types.AutosuggestResult": {
            "type": "object",
            "properties": {
                "coverage": {
                    "description": "Coverage is the fraction of input lines matched by this pattern (0.0–1.0).\nHeterogeneous streams will show multiple patterns each covering a subset.",
                    "type": "number"
                },
                "custom_patterns": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "parsed_logs": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "pattern": {
                    "type": "string"
                },
                "pattern_description": {
                    "type": "string"
                },
                "pattern_name": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "timestamp_field": {
                    "description": "TimestampField / TimestampLayout / TimestampSource carry log2grok's\nauto-derived timestamp hint when one was inferred from the chosen\nGrok body (HTTPDATE → \"timestamp\" + Go layout, TIMESTAMP_ISO8601 →\n\"ts\" + ISO layout, etc.). The frontend uses them to pre-select the\ntimestamp column in step 3 of the import wizard without a second\n/parse round-trip. Empty when log2grok could not infer one.",
                    "type": "string"
                },
                "timestamp_layout": {
                    "type": "string"
                },
                "timestamp_source": {
                    "type": "string"
                }
            }
        },
        "types.ErrorResponse": {
            "description": "Standardized error response structure used across all API endpoints",
            "type": "object",
            "properties": {
                "code": {
                    "description": "Error code for programmatic handling",
                    "type": "string"
                },
                "details": {
                    "description": "Additional error details",
                    "type": "string"
                },
                "error": {
                    "description": "Main error message",
                    "type": "string"
                },
                "status": {
                    "description": "Status will always be \"error\" for error responses",
                    "type": "string"
                }
            }
        },
        "types.FacetField": {
            "type": "object",
            "properties": {
                "distinct": {
                    "type": "integer"
                },
                "high_cardinality": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.FacetValue"
                    }
                }
            }
        },
        "types.FacetValue": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "truncated": {
                    "type": "boolean"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "types.FacetsResponse": {
            "type": "object",
            "properties": {
                "computed_over": {
                    "type": "integer"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.FacetField"
                    }
                },
                "sampled": {
                    "type": "boolean"
                }
            }
        },
        "types.GrokPatternRequest": {
            "description": "Request structure for creating or updating Grok patterns",
            "type": "object",
            "properties": {
                "custom_patterns": {
                    "description": "Map of custom pattern definitions used by this pattern",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "Human-readable description of the pattern",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the Grok pattern",
                    "type": "string"
                },
                "pattern": {
                    "description": "The Grok pattern string",
                    "type": "string"
                },
                "priority": {
                    "description": "Priority of the pattern (higher numbers are matched first)",
                    "type": "integer"
                },
                "timestamp_config": {
                    "description": "TimestampConfig is the user's preferred resolution for this\npattern. Persisted in a logsonic-side file (log2grok's library\nschema doesn't carry it) and re-applied on subsequent imports.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/timeresolve.Resolution"
                        }
                    ]
                }
            }
        },
        "types.GrokPatternResponse": {
            "description": "Response structure for Grok pattern operations",
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message if status is \"error\"",
                    "type": "string"
                },
                "patterns": {
                    "description": "List of Grok patterns",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.GrokPatternRequest"
                    }
                },
                "status": {
                    "description": "Status of the operation",
                    "type": "string"
                }
            }
        },
        "types.IngestFileRequest": {
            "type": "object",
            "properties": {
                "include_rotated": {
                    "description": "IncludeRotated also ingests app.log.N / app-YYYY-MM-DD.log siblings,\noldest first, under the same session and source.",
                    "type": "boolean"
                },
                "log_file_name": {
                    "description": "Deprecated: use Path.",
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "types.IngestFileResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                },
                "members": {
                    "description": "every file that will be read, in order",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "path": {
                    "description": "canonical path of the base file",
                    "type": "string"
                },
                "status": {
                    "description": "\"accepted\"",
                    "type": "string"
                }
            }
        },
        "types.IngestJob": {
            "type": "object",
            "properties": {
                "bytes_read": {
                    "type": "integer"
                },
                "bytes_total": {
                    "type": "integer"
                },
                "compression": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "lines": {
                    "type": "integer"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "path": {
                    "type": "string"
                },
                "rate_lines_per_s": {
                    "type": "number"
                },
                "rows_failed": {
                    "type": "integer"
                },
                "rows_stored": {
                    "type": "integer"
                },
                "session_id": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "types.IngestJobActionResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "\"cancelling\", or the job's terminal state if it had already finished",
                    "type": "string"
                }
            }
        },
        "types.IngestJobsListResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.IngestJob"
                    }
                }
            }
        },
        "types.IngestRequest": {
            "type": "object",
            "properties": {
                "logs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "types.IngestResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "failed": {
                    "type": "integer"
                },
                "filename": {
                    "type": "string"
                },
                "processed": {
                    "type": "integer"
                },
                "session_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "types.IngestSessionOptions": {
            "type": "object",
            "properties": {
                "custom_patterns": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "force_start_day": {
                    "type": "string"
                },
                "force_start_month": {
                    "type": "string"
                },
                "force_start_year": {
                    "type": "string"
                },
                "force_timezone": {
                    "type": "string"
                },
                "meta": {
                    "description": "Meta contains additional fields to be added to each log entry.\nThese fields are merged directly into the JSON output for each log.",
                    "type": "object",
                    "additionalProperties": true
                },
                "multiline": {
                    "description": "Multiline configures folding of physical lines into logical log\nrecords before pattern matching, for formats where a single log\nstatement spans multiple lines (stack traces, multi-line JSON,\netc). Nil/disabled preserves the historical one-line-per-record\nbehaviour. Folding is applied on /parse (including autosuggest)\nas well as ingest and live tail.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.MultilineConfig"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "pattern": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "smart_decoder": {
                    "type": "boolean"
                },
                "source": {
                    "type": "string"
                },
                "source_mtime": {
                    "description": "SourceMTime is the modification time of the source file when\nknown. Lets the resolver anchor year-less or 2-digit-year\ntimestamps against the file rather than wall-clock now.",
                    "type": "string"
                },
                "timestamp_config": {
                    "description": "TimestampConfig is the user-confirmed resolution from the import\nwizard. When nil, the resolver auto-derives defaults from a\nsample (legacy ForceStart* fields are still honoured).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/timeresolve.Resolution"
                        }
                    ]
                }
            }
        },
        "types.LogDistributionEntry": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "source_counts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "types.LogResponse": {
            "type": "object",
            "properties": {
                "available_columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "count": {
                    "type": "integer"
                },
                "end_date": {
                    "type": "string"
                },
                "facets": {
                    "description": "Facets is present only when the request asked for include_facets=true.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.FacetsResponse"
                        }
                    ]
                },
                "index_query_time": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "log_distribution": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.LogDistributionEntry"
                    }
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "offset": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "sort_by": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "time_taken": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "types.MultilineConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "header_pattern": {
                    "description": "HeaderPattern is a regular expression; required when Mode==\"header\".\nA line matching it starts a new record, everything else is folded\ninto the preceding record. Continuation lines are joined with\nspaces (log2grok's JoinMultilineStrings behaviour).",
                    "type": "string"
                },
                "max_bytes": {
                    "type": "integer"
                },
                "max_lines": {
                    "description": "MaxLines caps continuation lines folded into one record (default\n100). MaxBytes caps the folded record's byte length (default 1MiB).",
                    "type": "integer"
                },
                "mode": {
                    "description": "\"header\" | \"indent\"",
                    "type": "string"
                }
            }
        },
        "types.ParseRequest": {
            "type": "object",
            "properties": {
                "custom_patterns": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "grok_pattern": {
                    "type": "string"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "multi": {
                    "description": "Multi requests heterogeneous-stream detection: when true and no\nGrokPattern is supplied, autosuggest runs log2grok's DiscoverMulti\nand returns an ordered set of standalone patterns (results[0] is the\ndominant one) that together cover the input. When false (default)\nautosuggest runs the single-pattern Discover, preserving the\nhistorical one-result behaviour.",
                    "type": "boolean"
                },
                "session_options": {
                    "$ref": "#/definitions/types.IngestSessionOptions"
                }
            }
        },
        "types.ParseResponse": {
            "description": "Response from the parse endpoint, containing parsed logs and potential error information",
            "type": "object",
            "properties": {
                "custom_patterns": {
                    "description": "Custom patterns used (optional)",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "failed": {
                    "description": "Number of log lines that failed to parse",
                    "type": "integer"
                },
                "logs": {
                    "description": "Array of parsed log entries, where each entry is a key-value map",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "pattern": {
                    "description": "Pattern used for parsing (optional)",
                    "type": "string"
                },
                "pattern_description": {
                    "description": "Description of the pattern (optional)",
                    "type": "string"
                },
                "processed": {
                    "description": "Number of log lines processed",
                    "type": "integer"
                },
                "status": {
                    "description": "Status of the parse operation\n@Example \"success\" or \"error\"",
                    "type": "string"
                },
                "timestamp_inference": {
                    "description": "TimestampInference describes how the resolver interpreted the\ntimestamps in this sample. Drives the wizard's diagnostic chip\nand live preview. Empty when no logs were provided.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/timeresolve.Inference"
                        }
                    ]
                }
            }
        },
        "types.PreviewFileRequest": {
            "type": "object",
            "properties": {
                "lines": {
                    "description": "Lines caps how many lines to read; default 100, capped server-side.",
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "types.PreviewFileResponse": {
            "type": "object",
            "properties": {
                "approx_lines": {
                    "type": "integer"
                },
                "compressed": {
                    "type": "string"
                },
                "lines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "size_bytes": {
                    "type": "integer"
                }
            }
        },
        "types.SavedQuery": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "time": {
                    "$ref": "#/definitions/types.WorkspaceTime"
                }
            }
        },
        "types.SourceEntry": {
            "type": "object",
            "properties": {
                "bytes_raw": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "day_rows": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "days": {
                    "description": "Days lists every day-index holding rows for this source (sorted);\nDayRows is the per-day count behind it, which is what lets a rebuild\nafter a prune or a row delete touch only the affected days.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "first_ts": {
                    "type": "string"
                },
                "imports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.SourceImport"
                    }
                },
                "last_ts": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "origin": {
                    "$ref": "#/definitions/types.SourceOrigin"
                },
                "pattern": {
                    "type": "string"
                },
                "pattern_name": {
                    "type": "string"
                },
                "rows": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "types.SourceImport": {
            "type": "object",
            "properties": {
                "at": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "rows": {
                    "type": "integer"
                }
            }
        },
        "types.SourceOrigin": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "types.SourceRowsEntry": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "rows": {
                    "type": "integer"
                }
            }
        },
        "types.SourcesResponse": {
            "type": "object",
            "properties": {
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.SourceEntry"
                    }
                }
            }
        },
        "types.SuggestResponse": {
            "type": "object",
            "properties": {
                "combined_coverage": {
                    "description": "CombinedCoverage is the fraction of input lines covered by the union\nof all returned patterns (0.0–1.0). It only differs from\nResults[0].Coverage when a multi-pattern set was requested (Multi)\nand more than one pattern was returned. Omitted for single-pattern\nresponses.",
                    "type": "number"
                },
                "multiline": {
                    "description": "Multiline is the folding config used for this suggestion. Set when\nthe caller supplied one, or when /parse auto-detected a common\ncontinuation style (syslog / ISO 8601 / indent) because folding\nproduced a better library match than treating each physical line\nas its own record.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.MultilineConfig"
                        }
                    ]
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.AutosuggestResult"
                    }
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.SystemInfoResponse": {
            "type": "object",
            "properties": {
                "app": {
                    "description": "App identifies the server binary (from goreleaser ldflags). The UI\nprefers this over its own bundle version so a stale app shell or a\nmismatched CLI is visible in the status bar and About page.",
                    "type": "object",
                    "properties": {
                        "build_date": {
                            "type": "string"
                        },
                        "commit": {
                            "type": "string"
                        },
                        "version": {
                            "type": "string"
                        }
                    }
                },
                "status": {
                    "type": "string"
                },
                "storage_info": {
                    "type": "object",
                    "properties": {
                        "available_dates": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "source_names": {
                            "description": "SourceNames is kept for existing clients; Sources carries the\nsame names with their row counts from the sources catalog.",
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "sources": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.SourceRowsEntry"
                            }
                        },
                        "storage_directory": {
                            "type": "string"
                        },
                        "storage_size_bytes": {
                            "type": "integer"
                        },
                        "total_indices": {
                            "type": "integer"
                        },
                        "total_log_entries": {
                            "type": "integer"
                        }
                    }
                },
                "system_info": {
                    "type": "object",
                    "properties": {
                        "architecture": {
                            "type": "string"
                        },
                        "go_version": {
                            "type": "string"
                        },
                        "hostname": {
                            "type": "string"
                        },
                        "memory_usage": {
                            "type": "object",
                            "properties": {
                                "alloc_bytes": {
                                    "type": "integer"
                                },
                                "num_gc": {
                                    "type": "integer"
                                },
                                "sys_bytes": {
                                    "type": "integer"
                                },
                                "total_alloc_bytes": {
                                    "type": "integer"
                                }
                            }
                        },
                        "num_cpu": {
                            "type": "integer"
                        },
                        "os_type": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "types.Workspace": {
            "type": "object",
            "properties": {
                "color_rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.WorkspaceColorRule"
                    }
                },
                "column_widths": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "facet_fields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "favorite": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "saved_queries": {
                    "description": "SavedQueries are named query+time+source snapshots a user starred\nwhile investigating in this workspace (spec now-03). Omitted (not an\nempty array) on a workspace with none, so a pre-now-03 workspace file\nunmarshals with a nil slice, not a JSON parse error.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.SavedQuery"
                    }
                },
                "sort_by": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "string"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "time": {
                    "$ref": "#/definitions/types.WorkspaceTime"
                },
                "updated_at": {
                    "type": "string"
                },
                "visualization": {
                    "$ref": "#/definitions/types.WorkspaceVisualization"
                }
            }
        },
        "types.WorkspaceColorRule": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "field": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "types.WorkspaceListResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "workspaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Workspace"
                    }
                }
            }
        },
        "types.WorkspaceResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "workspace": {
                    "$ref": "#/definitions/types.Workspace"
                }
            }
        },
        "types.WorkspaceTime": {
            "type": "object",
            "properties": {
                "custom_relative_count": {
                    "type": "integer"
                },
                "custom_relative_unit": {
                    "type": "string"
                },
                "end": {
                    "type": "string"
                },
                "mode": {
                    "description": "\"relative\" or \"absolute\"",
                    "type": "string"
                },
                "relative": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "types.WorkspaceVisualization": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "LogSonic API",
	Description:      "API for ingesting, storing, and querying log data with Grok pattern support",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
